blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/tuxtechlab/tuxtechiaac/discussions
    about: Need help selfhosting or ask a general question about the project? Open a discussion.
  - name: Discord
    url: https://discord.gg/your-invite-code
    about: Join our Discord community for real-time discussions and support.